/** @type {import('tailwindcss').Config} */
const colorPalette = {
  background: "#0b1326",
  "on-tertiary-fixed": "#2c1700",
  secondary: "#adc6ff",
  "secondary-fixed-dim": "#adc6ff",
  "on-secondary-fixed-variant": "#004395",
  outline: "#958ea0",
  "surface-dim": "#0b1326",
  "outline-variant": "#494454",
  "surface-tint": "#e84c1b",
  "surface-container-highest": "#2d3449",
  "on-error": "#690005",
  "on-tertiary": "#482900",
  "surface-bright": "#31394d",
  "on-primary-container": "#340080",
  "on-surface": "#dae2fd",
  "primary-fixed": "#e9ddff",
  "primary-fixed-dim": "#e84c1b",
  "surface-container-low": "#131b2e",
  "on-primary": "#3c0091",
  "inverse-surface": "#dae2fd",
  "inverse-on-surface": "#283044",
  "secondary-fixed": "#d8e2ff",
  "surface-container-high": "#222a3d",
  "on-background": "#dae2fd",
  surface: "#0b1326",
  "inverse-primary": "#6d3bd7",
  primary: "#e84c1b",
  "surface-container-lowest": "#060e20",
  "on-primary-fixed-variant": "#5516be",
  "on-surface-variant": "#cbc3d7",
  "on-tertiary-container": "#3f2300",
  "error-container": "#93000a",
  error: "#ffb4ab",
  "on-tertiary-fixed-variant": "#673d00",
  "tertiary-fixed": "#ffdcbb",
  "on-secondary-container": "#e6ecff",
  tertiary: "#ffb869",
  "on-secondary-fixed": "#001a42",
  "on-primary-fixed": "#23005c",
  "primary-container": "#a078ff",
  "tertiary-container": "#ca801e",
  "surface-container": "#171f33",
  "on-error-container": "#ffdad6",
  "on-secondary": "#002e6a",
  "tertiary-fixed-dim": "#ffb869",
  "secondary-container": "#0566d9",
  "surface-variant": "#2d3449",
};

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: colorPalette,
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ["JetBrains Mono"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
