/** @type {import('tailwindcss').Config} */
const colorPalette = {
  background: "var(--background)",
  "on-tertiary-fixed": "var(--muted)",
  secondary: "var(--muted)",
  "secondary-fixed-dim": "var(--muted)",
  "on-secondary-fixed-variant": "var(--muted)",
  outline: "var(--border)",
  "surface-dim": "var(--surface)",
  "outline-variant": "var(--border)",
  "surface-tint": "var(--primary)",
  "surface-container-highest": "var(--surface)",
  "on-error": "var(--text)",
  "on-tertiary": "var(--muted)",
  "surface-bright": "var(--surface)",
  "on-primary-container": "var(--text)",
  "on-surface": "var(--text)",
  "primary-fixed": "var(--primary)",
  "primary-fixed-dim": "var(--primary)",
  "surface-container-low": "var(--surface)",
  "on-primary": "var(--text-on-primary)",
  "inverse-surface": "var(--text)",
  "inverse-on-surface": "var(--background)",
  "secondary-fixed": "var(--muted)",
  "surface-container-high": "var(--surface)",
  "on-background": "var(--text)",
  surface: "var(--surface)",
  "inverse-primary": "var(--primary)",
  primary: "var(--primary)",
  "surface-container-lowest": "var(--surface)",
  "on-primary-fixed-variant": "var(--text)",
  "on-surface-variant": "var(--muted)",
  "on-tertiary-container": "var(--muted)",
  "error-container": "var(--primary)",
  error: "var(--primary)",
  "on-tertiary-fixed-variant": "var(--muted)",
  "tertiary-fixed": "var(--muted)",
  "on-secondary-container": "var(--muted)",
  tertiary: "var(--primary)",
  "on-secondary-fixed": "var(--muted)",
  "on-primary-fixed": "var(--text)",
  "primary-container": "var(--primary)",
  "tertiary-container": "var(--primary)",
  "surface-container": "var(--surface)",
  "on-error-container": "var(--text)",
  "on-secondary": "var(--muted)",
  "tertiary-fixed-dim": "var(--muted)",
  "secondary-container": "var(--muted)",
  "surface-variant": "var(--border)",
};

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: colorPalette,
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ["JetBrains Mono"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
