
import { faker } from "@faker-js/faker";

const fakerMap: Record<string, () => string | number | boolean> = {
  "$guid": () => faker.string.uuid(),
  "$randomUUID": () => faker.string.uuid(),
  "$timestamp": () => Math.floor(Date.now() / 1000),
  "$isoTimestamp": () => new Date().toISOString(),
  "$randomEmail": () => faker.internet.email(),
  "$randomExampleEmail": () => faker.internet.exampleEmail(),
  "$randomUserName": () => faker.internet.userName(),
  "$randomPassword": () => faker.internet.password(),
  "$randomIP": () => faker.internet.ip(),
  "$randomIPV6": () => faker.internet.ipv6(),
  "$randomMACAddress": () => faker.internet.mac(),
  "$randomUserAgent": () => faker.internet.userAgent(),
  "$randomProtocol": () => faker.internet.protocol(),
  "$randomFirstName": () => faker.person.firstName(),
  "$randomLastName": () => faker.person.lastName(),
  "$randomFullName": () => faker.person.fullName(),
  "$randomPhoneNumber": () => faker.phone.number(),
  "$randomCity": () => faker.location.city(),
  "$randomStreetAddress": () => faker.location.streetAddress(),
  "$randomCountry": () => faker.location.country(),
  "$randomLatitude": () => faker.location.latitude(),
  "$randomLongitude": () => faker.location.longitude(),
  "$randomCompanyName": () => faker.company.name(),
  "$randomJobTitle": () => faker.person.jobTitle(),
  "$randomWord": () => faker.word.sample(),
  "$randomSentence": () => faker.lorem.sentence(),
  "$randomParagraph": () => faker.lorem.paragraph(),
  "$randomBoolean": () => faker.datatype.boolean(),
  "$randomInt": () => faker.number.int({ min: 0, max: 1000 }),
  "$randomFloat": () => faker.number.float(),
  "$randomHexColor": () => faker.color.rgb({ format: "hex" }),
  "$randomColor": () => faker.color.human(),
  "$randomPrice": () => faker.commerce.price(),
  "$randomProductName": () => faker.commerce.productName(),
  "$randomDepartment": () => faker.commerce.department(),
  "$randomAlphaNumeric": () => faker.string.alphanumeric(1),
  "$randomAbbreviation": () => faker.word.sample().toUpperCase(),
  "$randomLocale": () => faker.location.countryCode(),
  "$randomSemver": () => faker.system.semver(),
  "$randomNamePrefix": () => faker.person.prefix(),
  "$randomNameSuffix": () => faker.person.suffix(),
  "$randomJobArea": () => faker.person.jobArea(),
  "$randomJobDescriptor": () => faker.person.jobDescriptor(),
  "$randomJobType": () => faker.person.jobType(),
  "$randomPhoneNumberExt": () => faker.phone.number("##-###-###-####"),
  "$randomStreetName": () => faker.location.street(),
  "$randomCountryCode": () => faker.location.countryCode(),
  "$randomAvatarImage": () => faker.image.avatar(),
  "$randomImageUrl": () => faker.image.url(),
  "$randomAbstractImage": () => faker.image.urlLoremFlickr({ category: "abstract" }),
  "$randomAnimalsImage": () => faker.image.urlLoremFlickr({ category: "animals" }),
  "$randomBankAccount": () => faker.finance.accountNumber(),
  "$randomBankAccountName": () => faker.finance.accountName(),
  "$randomCreditCardMask": () => faker.finance.maskedNumber(),
  "$randomBankAccountBic": () => faker.finance.bic(),
  "$randomBankAccountIban": () => faker.finance.iban(),
  "$randomTransactionType": () => faker.finance.transactionType(),
  "$randomCurrencyCode": () => faker.finance.currencyCode(),
  "$randomCurrencyName": () => faker.finance.currencyName(),
  "$randomCurrencySymbol": () => faker.finance.currencySymbol(),
  "$randomBitcoin": () => faker.finance.bitcoinAddress(),
  "$randomCompanySuffix": () => faker.company.suffix(),
  "$randomBs": () => faker.company.buzzPhrase(),
  "$randomBsAdjective": () => faker.company.buzzAdjective(),
  "$randomBsBuzz": () => faker.company.buzzVerb(),
  "$randomBsNoun": () => faker.company.buzzNoun(),
  "$randomCatchPhrase": () => faker.company.catchPhrase(),
  "$randomDatabaseColumn": () => faker.database.column(),
  "$randomDatabaseType": () => faker.database.type(),
  "$randomDateFuture": () => faker.date.future(),
  "$randomDatePast": () => faker.date.past(),
  "$randomDateRecent": () => faker.date.recent(),
  "$randomWeekday": () => faker.date.weekday(),
  "$randomMonth": () => faker.date.month(),
  "$randomDomainName": () => faker.internet.domainName(),
  "$randomDomainSuffix": () => faker.internet.domainSuffix(),
  "$randomDomainWord": () => faker.internet.domainWord(),
  "$randomUrl": () => faker.internet.url(),
  "$randomFileName": () => faker.system.fileName(),
  "$randomFileType": () => faker.system.fileType(),
  "$randomFileExt": () => faker.system.fileExt(),
  "$randomFilePath": () => faker.system.filePath(),
  "$randomProduct": () => faker.commerce.product(),
  "$randomNoun": () => faker.word.noun(),
  "$randomVerb": () => faker.word.verb(),
  "$randomAdjective": () => faker.word.adjective(),
  "$randomWords": () => faker.word.words(),
  "$randomPhrase": () => faker.lorem.sentence(),
  "$randomLoremWord": () => faker.lorem.word(),
  "$randomLoremWords": () => faker.lorem.words(),
  "$randomLoremSentence": () => faker.lorem.sentence(),
  "$randomLoremSentences": () => faker.lorem.sentences(),
  "$randomLoremParagraph": () => faker.lorem.paragraph(),
  "$randomLoremParagraphs": () => faker.lorem.paragraphs(),
  "$randomLoremText": () => faker.lorem.text(),
  "$randomLoremSlug": () => faker.lorem.slug(),
};

export function resolveFakerVariable(key: string) {
  const resolver = fakerMap[key];
  return resolver ? resolver() : key;
}

export function resolveFaker(input: string): string {
  return input.replace(/\$[a-zA-Z0-9]+/g, (match) => String(resolveFakerVariable(match)));
}
